### ISSUE TITLE
Accessing buckets in regions that require Signature Version 4 fails

### ISSUE THREAD

**Issue by ttheune** [99designs/aws-vault#108]
> An error occurred (InvalidRequest) when calling the PutObject operation: You are attempting to operate on a bucket in a region that requires Signature Version 4.  You can fix this issue by explicitly providing the correct region location using the --region argument, the AWS_DEFAULT_REGION environment variable, or the region variable in the AWS CLI configuration file.  You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".

Dunno if this counts as a Feature Request or a Bug.  Guess it depends on your POV.  For my day-to-day use this is a "nice-to-have" but I can see it being a deal breaker for other users.

**Comment by lox** [comment]
Thanks for the report! I'm pretty sure that this is an `awscli` bug, `aws-vault` isn't interacting with s3 in any way, and it's setting `AWS_DEFAULT_REGION` anyway :) 

I suspect this is fixed by upgrading your awscli, I'm currently facing the same issue on another project.

Let us know so we can close the bug.

**Comment by lox** [comment]
I solved this by explicitly passing `--region $REGION` to commands btw.

**Comment by ttheune** [comment]
@lox `--region <other region>` works just fine :)  And I agree, I think it's actually a boto problem at this point of the chain.  I can replicate the problem using  both`aws-vault` and going directly with `aws`.  Thanks for looking into it!
