### ISSUE TITLE
Keychain Password wasn't copied

### ISSUE THREAD

**Issue by kevinburke** [99designs/aws-vault#109]
Hi,
I use 1Password to store secrets. Unfortunately Mac's Keychain password generator doesn't let you copy/paste passwords, so I just set a 30-character random password for the keychain and didn't manage to copy it properly into 1Password.

I'm now locked out of my aws-vault. This is fine - I don't need the credentials that are in it, but I'm trying to delete it ("aws-vault remove stage") and readd the profile (aws-vault add stage), and every time I'm getting prompted for my aws-vault Keychain password, which I don't have.

How can I blow away everything aws-vault and Keychain related and start over?

**Comment by kevinburke** [comment]
Aha, I figured out the answer with the help of the `--debug` flag. Delete these two files:

- $HOME/Library/Keychains/aws-vault.keychain
- $HOME/Library/Keychains/aws-vault.keychain-db

**Comment by pda** [comment]
> Delete these two files

Spot on. Aside: `*.keychain` was the file extension prior to macOS Sierra, and `*.keychain-db` is the file extension since then. The upgrade copies and leaves the old one behind, and Keychain framework code automatically maps `open("foo.keychain")` to `open("foo.keychain-db")`. More background in https://github.com/99designs/aws-vault/pull/85
