### ISSUE TITLE
Output session credentials into ~/.aws/credentials instead of ENV

### ISSUE THREAD

**Issue by dforsber-p** [99designs/aws-vault#189]
### Output session credentials into ~/.aws/credentials instead of ENV

Possibly overwriting the previous session. ENV is typically world readable, whilst the file is user readable. Also, easier integration with other tools.

**Comment by FernandoMiguel** [comment]
no, just no!
i dont want creds stored in clear text on disk!!

that's the all idea of the keychain

**Comment by dforsber-p** [comment]
Store the STS credentials, not long term. Passingn them to the env is readable to all users and processes in the machine.

**Comment by lox** [comment]
https://security.stackexchange.com/questions/14000/environment-variable-accessibility-in-linux/14009#14009

**Comment by lox** [comment]
> Passing them to the env is readable to all users and processes in the machine - during the time the process is running of course.

That's false on macOS/BSD or Linux, at least since about 2006. Not sure about windows. Environment variables can only be read by `root` or the user that owns the process. Using environment has the advantage of reducing the time they are live in memory. I'm not keen on storing them in the credentials file. Can you provide an example of how it improves tool integration?

**Comment by dforsber-p** [comment]
Great! I'm not up-to-date with that info. That then solves it in this case :).

**Comment by lox** [comment]
Thanks for filing the issue @dforsber-p, apologies for slightly terse reply, always welcome discussion on this stuff!

**Comment by dforsber-p** [comment]
Np, I completely understand.
