### ISSUE TITLE
(Dockerized aws-vault) aws-vault: error: Failed to get credentials for test: InvalidClientTokenId

### ISSUE THREAD

**Issue by segersniels** [99designs/aws-vault#192]
I am trying to setup docker aliases to limit dependencies on my OS to only Docker. I have a docker image which contains aws-cli + aws-vault. Is it possible to set credentials of aws-vault and sync the volume back to the host to use it again with other instances of the aws-vault container?

Cause now I'm trying to do:

`alias aws-vault='docker run --rm -ti -v /Users/me/.aws:/home/aws/.aws -v /Users/me/.dockerc/aws-vault:/home/aws/.awsvault sth-vault /home/aws/aws/env/bin/aws-vault'`

`aws-vault --backend=file add foo`

Which successfully creates the aws-vault keys file on both the host and container. But it seems that the new instances of the aws-vault container can not access the file created by aws-vault.

`aws-vault: error: Failed to get credentials for foo: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 994608c3-d0f8-11e7-9b3e-8d685b45761e`

**Comment by segersniels** [comment]
I seemed to have fixed this by downgrading to version 4.0.0 somehow.

**Comment by lox** [comment]
Hey @segersniels 👋🏻 That is odd! Sounds like you might have you volumes incorrect in docker? I don't believe it will be anything to do with the version of aws-vault you are using. 

Check out https://github.com/99designs/aws-vault/pull/194. I'm going to close this, but feel free to re-open if it turns out to be an aws-vault issue.
