### ISSUE TITLE
aws-vault server sticks around longer than necessary

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#201]
When using aws-vault exec with the --server flag, the server process sticks around even once the subshell has gone away.

```bash
$ aws-vault exec --server contests
$ exit
$ ps a | grep aws-vault
46031 s000  S      0:00.00 sudo -b aws-vault server
46032 s000  S      0:00.04 aws-vault server
46173 s000  R+     0:00.00 grep aws-vault
```

**Comment by lox** [comment]
That is by design. The server is a dumb proxy that listens on the metadata address and forwards requests to the ephemeral server that runs in the `aws-vault exec` process.

**Comment by mtibben** [comment]
I think though that aws-vault (as a good parent process) should be responsible for stopping it when it's no longer required, or alternatively we should be giving control of it to launchctl

**Comment by lox** [comment]
The issue is it needs root access to launch. I wanted to avoid prompting for root creds constantly. 

Thoughts @pda?

**Comment by pecigonzalo** [comment]
I agree about the constant promts, maybe we can have 
A) a parameter (remain or not)
B) a way to terminate it like `aws-vault server stop` and start or similar (start is automatically done if `aws-vault exec --server $profile`

**Comment by tlaukkan** [comment]
Any progress on this one?

**Comment by daneah** [comment]
I find that occasionally the process that sticks around (it's `aws-vault proxy`, these days) contributes heavily to the CPU load of my machine—this is typically when aws-vault exits of its own accord rather than when I exit the subshell explicitly, though. That's perhaps a separate issue I could report, but I would agree that I normally expect a process that creates a subshell to clean itself up when that subshell is exited.
