### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by lox** [99designs/aws-vault#23]
Support for Linux users, whether command-line or desktop environment users. 

Todo:
- [x] Implement KWallet4 keyring backend
- [ ] Implement KWallet5 keyring backend
- [ ] Implement gpg-agent backend
- [x] Implement encrypted file backend
- [x] Release process needs to build linux binaries

**Comment by ketzacoatl** [comment]
With Go previously installed on Linux (Ubuntu Trusty, AMD64), I was able to build aws-vault with the following:

```
mkdir -p /home/user/.golang/src/github.com/99designs/
cd /home/user/.golang/src/github.com/99designs/
git clone https://github.com/99designs/aws-vault/
cd aws-vault
export GOPATH=/home/user/.golang
export GOROOT=/usr/local/go
go get
make
```

`aws-vault --help` works, but I haven't yet gotten further (need to add kwallet).

```
aws-vault
usage: aws-vault [<flags>] <command> [<args> ...]

A vault for securely storing and accessing AWS credentials in development environments.

Flags:
  --help             Show context-sensitive help (also try --help-long and --help-man).
  --debug            Show debugging output
  --prompt=terminal  Prompt driver to use [terminal]
  --version          Show application version.

Commands:
  help [<command>...]
    Show help.

  add [<flags>] <profile>
    Adds credentials, prompts if none provided

  ls
    List profiles

  exec [<flags>] <profile> [<cmd>] [<args>...]
    Executes a command with AWS credentials in the environment

  rm [<flags>] <profile>
    Removes credentials, including sessions

  login [<flags>] <profile>
    Generate a login link for the AWS Console

  server
    Run an ec2 instance role server locally
```

**Comment by lox** [comment]
Thanks for trying it out @ketzacoatl, what secret store are you hoping to use it with? Definitely need to get better feedback into the tool on what secret stores are available and what it's using!

**Comment by ketzacoatl** [comment]
@lox thanks for checking in, I would be happy to provide input. ATM I am evaluating `aws-vault` as a tool for use in a team environment, and I am interested in the simple/functional route, and a cross-platform solution to the team's need for AWS credential management across multiple AWS accounts, regions, and environments, and with MFA in the workflow.

On Linux, it seems `aws-vault` only supports kwalletd ATM, and I am on gnome, so I went on a short escapade in an attempt to install/run that with `aws-vault` in docker. That didn't work all that well, making loud noises about dbus and all that. While I have not written software that uses dbus, as a user of various desktop tools which do use dbus, I have grown wary of applications dependent on dbus, and it generally means cross-platform uses are severely restricted. kwalletd also seemed to be dependent on various desktop-only applications/capabilities, which means the `aws-vault` cli tool would then require a full desktop environment for general use.

I would love to advocate for a simpler path. Cross-platform support means flexibility to run the tool regardless of the particulars of my environment (and in this case, because of kwalletd and dbus, etc, cross-platform includes the desktop environment). If I can build the code on the OS I am running, I should be able to use your wonderful tool. Storing credentials securely is wonderful, though many existing tools end up requiring there be at least a few "root" creds in plaintext, in order to use the MFA workflows.

For example, I would love to be able to use `aws-vault` without the requirement to use the OS's "default secret keystore" (there is no such thing, this is a concept of the various desktop environments). 
In this case, `aws-vault` could store its data in a simple plaintext YAML/etc file or sqlitedb. This would allow for easier testing, and it would allow those users who are not on a "supported" platform to continue using the product while `aws-vault` is extended to support specific keystores. Plenty of people use Open/Free/etc/BSD, and removing this limitation would open `aws-vault` to those users as well.

Going back to keystores on linux.. https://wiki.gnome.org/Projects/Libsecret makes my point well.. if `aws-vault` uses libsecret to be "flexible", we've then got `aws-vault` --> (dbus? -->) libsecret --> dbus --> "Secret Service" (either gnome-keyring and ksecretservice). Doesn't this start to seem a bit too much abstraction and complication, places to fail an integration or version match, etc?

I love storing secrets securely, but for security, I find trust through simplicity and clarity. I have little faith in that amount of redirection to do so correctly and securely, and I would prefer `aws-vault` make use of a pluggable storage backend such that plaintext YAML files, straight up GPG, or gnome/kde-secret services could all be used/co-exist together.

**Comment by lox** [comment]
I completely forgot to respond @ketzacoatl, apologies. I think a platform independent backend would be great. I'd probably lean towards Amazon's default format for `~/.aws/credentials`, but then encrypted and named something like `~/.aws/credentials.aws-vault`. 

I'd been hoping someone would come along who actively uses gnome/kde and understood the ecosystem around the tools, but I suspect there is too much fragmentation to easily support a wide variety of uses.

**Comment by ptolemy428** [comment]
@lox, AWS vault is a great tool. To make it easier to use on Linux paltform, can we introduce an option to accept the AWS access key and Id as command args. In this case, the key encryption is completely decoupled and totally up to the user. The key can be decrypted on the fly (say with gpg) and passed to aws-vault using xargs. In this case, we do not have to worry abt which keyring implementation the user uses and have to wait for the support of that to be implemented.

**Comment by lox** [comment]
@ptolemy428 interesting idea, could you provide some more concrete examples of how the command flow for that would look? At this stage I am keen on a simple file backed, and possibly a gpg-agent one.

**Comment by lox** [comment]
FYI @ketzacoatl the latest release contains support for local credentials stored encrypted in `$HOME/.awsvault/keys/`.

**Comment by ketzacoatl** [comment]
thanks for the heads up @lox, will check it out!

**Comment by gsterjov** [comment]
I've added Secret Service support in this PR: https://github.com/99designs/aws-vault/pull/98
Only tested in Gnome so far.

**Comment by ChrisFernandez** [comment]
so reading on this, I will like to use aws vault because some coworkers use it, but I am on a linux system and our build process uses aws vault.. an option is to check enviroment and use something else but if I can avoid that will be much better... what are my options of any running Ubuntu 16.10 with unity.

**Comment by lox** [comment]
@ChrisFernandez you could use the file backend immediately, there are several people using it. Alternately, you could use the Secret Service support that @gsterjov built. Let us know how you go, open up a new ticket if you have issues.

**Comment by ChrisFernandez** [comment]
@lox thanks I will do that. do we need to change anything on our side so it picks up the alternate way?

**Comment by gsterjov** [comment]
@ChrisFernandez I just set the env var to my preferred backend. You should be able to use it unchanged that way.
```
AWS_VAULT_BACKEND=secret-service
```
Should be the same for the file backend as well, but I think that's the default in linux anyway

**Comment by lox** [comment]
I'm going to close this in favor of more specific issues for future linux features.
