### ISSUE TITLE
lack of AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by frezbo** [99designs/aws-vault#248]
aws-vault should set AWS_PROFILE environment variable also with the other env vars:
```
~ (aws:gov)(kc)$ aws-vault exec gov -- printenv AWS_REGION
us-gov-west-1
~ (aws:gov)(kc)$ aws-vault exec gov -- printenv AWS_PROFILE
~ (aws:gov)(kc)$ 
```

**Comment by lox** [comment]
Yup, apologies, I didn’t get a chance to reply, but that’s why it doesn’t set a profile!

**Comment by rdonkin** [comment]
With some other tools such as [assume-role](https://github.com/remind101/assume-role), I have found that the way they set `AWS_PROFILE` as well as the credentials vars for a temporary session can cause confusion - e.g. the [Serverless Framework](http://serverless.com) CLI tool will use the `AWS_PROFILE` var (if set) in preference to the session credentials, which in my setup caused problems because the `AWS_PROFILE`.

I think the code here is fine, as it unsets the inherited `AWS_PROFILE` env variable, and sets it based on (presumably) command line specified profile, so this var will be in sync with the session credentials.  

Maybe someone can clarify this, then it could be documented.

**Comment by frezbo** [comment]
I agree with @lox the `AWS_PROFILE` needs to be unset. Sorry for causing confusion. It was that the tool I used was having a bug.
