### ISSUE TITLE
aws-vault doesn't work with aliases

### ISSUE THREAD

**Issue by nwalke** [99designs/aws-vault#272]
I use terraform a lot and have it aliased to just `t`.  This doesn't seem to work in `aws-vault` however.

```
➜ t version
Terraform v0.11.7
```

```
➜ aws-vault exec home -- t version
aws-vault: error: exec: "t": executable file not found in $PATH
```

Anything I need to do to get this to work properly?

**Comment by kevinburkeomg** [comment]
maybe try `aws-vault exec home -- bash -c 't version'` ?

**Comment by nwalke** [comment]
Interestingly that did not work as expected
```
➜ t version
Terraform v0.11.7
```
```
➜ aws-vault exec home -- bash -c `t --version`
Usage: terraform [--version] [--help] <command> [args]
```

**Comment by pda** [comment]
`aws-vault exec …` doesn't execute via a shell, it [invokes the command directly](https://github.com/99designs/aws-vault/blob/a56c96b41bc539c4fdea0dba6f6056c212d67d5b/cli/exec.go#L146).

I don't think aliases will ever be supported via `aws-vault exec`. If it's really important, you could create a `/usr/local/bin/t` symlink to `terraform`.

(@nwalke Are those backticks instead of single or double quotes around your `bash -c` argument?)

**Comment by nwalke** [comment]
Making the symlink solves this for me!

They were backticks, single quotes caused it to not see the command?  iunno... I'm just happy it works the way I want.  :)

**Comment by pda** [comment]
Alternatively use a shell function instead of an alias:

```sh
avt() {
  profile=$1; shift
  aws-vault exec $profile -- terraform "$@"
}

avt home version
# runs aws-vault exec home -- terraform version
```
