### ISSUE TITLE
Passphrase prompt is hidden when piping or redirecting output

### ISSUE THREAD

**Issue by robert-claypool** [99designs/aws-vault#405]
README gives the example `aws-vault exec home -- env | grep AWS`, but `aws-vault` outputs a passphrase prompt which is hidden when a pipe or redirect is used.

```Shell
# Shows prompt:
aws-vault exec home -- env
# Hidden prompt:
aws-vault exec home -- env | grep AWS
# Hidden prompt:
aws-vault exec home -- env > env.txt
```

I would suggest a note in README for less experienced shell users, or is there a better work-around?

**Comment by hlakkala** [comment]
+1 for this.

Actually just battling with a similar thing myself. If I run aws-vault as part of a Bash script the MFA prompt either just flashes by (the execution doesn't stop to wait for input) or when redirecting errors to output is shown in the reply.

1) When there's no redirection of stderr, the MFA prompt is shown on the terminal but the script doesn't wait for an answer.
`reply_json=$(aws-vault exec "$account_id" -- aws health describe-events --region us-east-1)`

2) When redirection stderr to stdout the MFA prompt goes to the reply (reply_json).
`reply_json=$(aws-vault exec "$account_id" -- aws health describe-events --region us-east-1 2>&1)`

What would be the correct way to use aws-vault, so that MFA prompting would work? After running some other command before this and giving the MFA code for it, this works fine.

**Comment by frezbo** [comment]
you can `echo <mfa_key> | aws-vault exec `

**Comment by jonscheiding** [comment]
Note: @hlakkala and @robert-claypool are describing different issues.

The MFA prompt is written to stderr, per #56.  (@hlakkala I could not actually reproduce the behavior you are seeing - it allows me to enter my MFA token.)

But I'm running aws-vault on Ubuntu, and using the default passphrase-protected local file storage.  So in addition to the MFA prompt, there is also a passphrase prompt.  That prompt is written to stdout.

So this creates the following behavior:

```
$ JSON=$(aws-vault exec myprofile --json)
# I enter my passphrase
Enter token for arn:aws:iam::000000000000:mfa/jonscheiding: 123456
$ echo $JSON
Enter passphrase to unlock /home/jonscheiding/.awsvault/keys/: {"Version":1,"AccessKeyId":"ABCDEFGHIJKLMNOPQRST","SecretAccessKey":"...","SessionToken":"...","Expiration":"2019-09-13T17:33:15Z"}
```

**Comment by gdamjan** [comment]
maybe even better if prompts and input are read from `/dev/tty` explicitly.

> /dev/tty is a special file, representing the terminal for the current process.
