### ISSUE TITLE
Add environment variable for default command for exec

### ISSUE THREAD

**Issue by hoegertn** [99designs/aws-vault#406]
I would love using `aws-vault exec profile` instead of specifying the bash all the time, but instead of creating a login shell the default it just to run `bash`. It would be great to be able to specify another default command or for `exec` to run a login shell (`bash -l`).

**Comment by mtibben** [comment]
Hey @hoegertn aws-vault uses the `SHELL` env var as the default

**Comment by willejs** [comment]
@mtibben I think the problem is that it uses the shell env var, but it does not create a login shell, passing -l so you have to run `aws-vault exec profile -- $SHELL -l` every time you want an interactive shell that picks up your shells profile etc. I think instead it should add a `-l` onto the end of $SHELL ? I think most shells support this?

**Comment by mtibben** [comment]
@willejs aws-vault does pass the environment through to the new process, you'll just need to make sure your `.bashrc` or `.zshrc` is adding the local functions or variables like your PS1 prompt.

**Comment by mtibben** [comment]
Added docs here https://github.com/99designs/aws-vault/commit/be6e1b6d6f16840f8152cf43e680d0d9f89c84a9. Does this solve your problem @hoegertn @willejs ?
