### ISSUE TITLE
Provide darwin binary in parallel with dmg

### ISSUE THREAD

**Issue by olfway** [99designs/aws-vault#467]
Could you, please, also provide darwin binary on the releases page?

**Comment by mtibben** [comment]
Catalina now requires notorization in order to run a binary. The problem is the Apple notorization "ticket" can't be stapled to the binary, only to the DMG. Catalina can still verify the binary, however it requires access to the apple notorization service to verify. 

So while I could include the binary in releases, there's a possibility Catalina can't run it if they don't have internet access or something else goes wrong. As this is difficult to explain, it will ultimately lead to support issues. So I'd prefer to leave it in a notorized DMG for maximum compatibility.
