### ISSUE TITLE
Restore OIDC token caching 

### ISSUE THREAD

**Issue by mtibben** [99designs/aws-vault#571]
#569 removed tests and caching for the OIDC token, we should restore

/cc @itsdalmo @rickardl

**Comment by mtibben** [comment]
@itsdalmo 
> The two levels of caching was there because the start_url is the same for multiple profiles as you say. What was being cached was a device ID and an access token that could be used to exchange for role credentials, and by removing the caching users will need to go through login-flow (opening the browser and clicking sign-in etc) every time the role credentials expire (typically 1h) instead of just when the access token expires (e.g. every 8h). The device ID and access tokens are cached in the v2 AWS CLI as well, so I think AWS expects these values to be "long lived".

Sounds like the OIDC is the credential with friction? We should probably just cache that then instead of the SSO credentials, because the SSO credentials can be generated on-demand?

**Comment by flyinprogrammer** [comment]
> SSO credentials, because the SSO credentials can be generated on-demand?

In my, humble and still learning, opinion, we might want to cache both?

caching OIDC will mean not having to open a browser across multiple profiles that share the same sso_start_url - i.e. login

caching SSO credentials will mean lower latency when using the AWS API, just like today, because we can use those credentials until they expire.
