### ISSUE TITLE
unknown long flag '--ecs-server'

### ISSUE THREAD

**Issue by asmirnou** [99designs/aws-vault#614]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

```
aws-vault exec api --ecs-server
aws-vault: error: unknown long flag '--ecs-server', try --help
```

What am I missing?

**Comment by ajkerrigan** [comment]
Hey there @asmirnou - the `--ecs-server` flag was added for v6.0 which is still in beta. If you've installed AWS Vault from a package manager or otherwise fetched the latest official release, you may be working with v5.x (`aws-vault --version` could help confirm one way or the other).

If that's the case, hopefully grabbing the latest v6.0 pre-release ([v6.0.0-beta5](https://github.com/99designs/aws-vault/releases/tag/v6.0.0-beta5) as of today) will help get `--ecs-server` working for you!

**Comment by asmirnou** [comment]
Thanks.
