### ISSUE TITLE
Issue with AWS SSO & credential_process

### ISSUE THREAD

**Issue by PGBI** [99designs/aws-vault#651]
I'm trying to use `aws-vault` with AWS SSO. I'm also trying to leverage `credential_process` to make the use of `aws-vault` transparent and have it used automatically by third party tools like `terraform`.

So my config is a merge between the examples given in:
* https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process and
* https://github.com/99designs/aws-vault/blob/master/USAGE.md#aws-single-sign-on-aws-sso

```
[profile main]
sso_start_url      = xxx
sso_region         = us-west-2
sso_account_id     = xxx
sso_role_name      = Administrator
credential_process = /usr/local/bin/aws-vault exec main --json --prompt=osascript
```
With this above config, things aren't working as I expect. It seems like the `credential_process` command is never invoked:
```
$ aws s3 ls --profile main

Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.
```
--
I actually managed to do what I need with the following config:
```
[profile main]
sso_start_url      = xxx
sso_region         = us-west-2
sso_account_id     = xxx
sso_role_name      = Administrator

[profile main-vault]
credential_process = /usr/local/bin/aws-vault --debug exec main --json --prompt=osascript
```
```
$ aws s3 ls --profile main-vault
<list of buckets>
```

It works, but I don't understand why :)

What is wrong with the first version of the config file? Is that a bug or simply me misunderstanding how aws-vault works? Is the second config the correct way to set things up for my use case?

**Comment by FernandoMiguel** [comment]
arent you trying to run the same profile twice, as in a loop?

**Comment by PGBI** [comment]
I have a profile configured with AWS SSO. That profile is called `main`. It works well with aws-vault.

Now I also want to avoid having to append every aws or terraform command I run with `aws-vault exec`. So I added that `credential_process = aws-vault exec main --json --prompt=osascript` line to the config as explained in the doc [here](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process), which lead to the error I posted in my initial post.

**Comment by ajkerrigan** [comment]
> What is wrong with the first version of the config file? Is that a bug or simply me misunderstanding how aws-vault works? Is the second config the correct way to set things up for my use case?

Hi @PGBI, I'll chip in here only because I've tried the same thing you did and seen other people try it too. It feels like it should work, right? Here's my take on why the first version fails (ymmv, I could be missing key bits):

* When the AWS CLI looks for profile credentials, it goes through a chain of providers in order and stops when it finds the first one that doesn't fail.
* The SSO provider [comes before the credential process provider](https://github.com/boto/botocore/blob/e5a2b4f5dcc8b6ef2f241064306e02c7f8906a58/botocore/credentials.py#L150-L159).
* The SSO provider only fails (returns `None`) [if there's no SSO configuration](https://github.com/boto/botocore/blob/e5a2b4f5dcc8b6ef2f241064306e02c7f8906a58/botocore/credentials.py#L2099-L2102). Otherwise it returns a "we'll sort out the details later" response.

So whether you've got an active SSO session or not, the fact that you've got SSO _configured_ means it won't fall through to the credential process provider.

You already found one way to work around that - put your credential process in a separate profile. In case it's useful as an addition/alternative, the [--ecs-server](https://github.com/99designs/aws-vault/blob/daaa1ab07e5d5cb536cb2b5531142d4b7fe28f99/USAGE.md#--ecs-server) option seems to work pretty nicely with Terraform. Running `aws-vault exec --ecs-server main` can give you a shell locked into your target profile, which refreshes credentials behind the scenes as needed. From there most of your aws/terraform/etc commands should work transparently. (Caveat: As noted in the usage docs, apps or SDKs that don't support `AWS_CONTAINER_CREDENTIALS_FULL_URI` don't play nicely with `--ecs-server`)

**Comment by FernandoMiguel** [comment]
You don't really need ecs server for terraform.
Exec is more than enough if you have a ttl of 8h

**Comment by mtibben** [comment]
Sounds like this is sorted for you now @PGBI, feel free to contribute improvements to the docs if you can

**Comment by PGBI** [comment]
@mtibben I think I got a better understanding thanks to @ajkerrigan about why the first version of my config didn't work as I intended to.

I'm still unsure though if the second version of my config (which works as I intend) is an ugly workaround I should avoid at all cost and if there is a better "official" way to do it. If I could get some sort of sign off on that config from an owner of this repository, I would gladly open a PR to improve the documentation.
