### ISSUE TITLE
The homebrew cask doesn't install the shell autocompletions.  

### ISSUE THREAD

**Issue by schmod** [99designs/aws-vault#688]
- [x] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

The current Homebrew cask for this package does not install the corresponding [shell-autocompletion scripts](https://github.com/99designs/aws-vault/tree/master/contrib/completions).  

It appears that casks generally don't support this, but as an open-source CLI app, it probably makes sense to convert this package to be a formula anyway (if nothing else, it'll help to prepare for native ARM support).

**Comment by mtibben** [comment]
> The current Homebrew cask for this package does not install the corresponding [shell-autocompletion scripts](https://github.com/99designs/aws-vault/tree/master/contrib/completions).

Autocompletion scripts can be generated from the CLI, see https://github.com/99designs/aws-vault/blob/master/USAGE.md#shell-completion

> as an open-source CLI app, it probably makes sense to convert this package to be a formula anyway

The binary needs to be signed in order to [avoid extra keychain prompts](https://github.com/99designs/aws-vault#development). Formulas don't allow that.

An alternative solution could be creating a dedicated tap.
