### ISSUE TITLE
Upgrade from 6.1.0 to 6.2.0 breaks file backend

### ISSUE THREAD

**Issue by isugimpy** [99designs/aws-vault#700]
As mentioned in #663, the upgrade from 6.1.0 to 6.2.0 causes a failure to decrypt in the file backend.  This happened with the upgrade from v5 to v6 as well.
`aws-vault: error: exec: Failed to get credentials for Ads_AccountAdmin: aes.KeyUnwrap(): integrity check failed.`

cc: @phyber

**Comment by mtibben** [comment]
The downstream issue is https://github.com/dvsekhvalnov/jose2go/issues/26 and the fix was applied in aws-vault 6.2.0. This has caused some file backends to break. The solution is to use the old version of aws-vault to retrieve the credentials (e.g. `aws-vault exec --no-session profile -- env | grep AWS`, and recreate using the latest version of aws-vault
