### ISSUE TITLE
aws-vault: error: exec: Failed to get credentials for %profile-name%: unexpected end of JSON input

### ISSUE THREAD

**Issue by vtvz** [99designs/aws-vault#821]
- [X] I am using the latest release of AWS Vault
```
$ aws-vault --version
v6.3.1
```
- [X] I have provided my `.aws/config` (redacted if necessary)
```
[profile %profile-name%]
sso_start_url = https://%something-there%.awsapps.com/start
sso_region = eu-west-1
sso_account_id = %account-id%
sso_role_name = AWSAdministratorAccess
region = eu-west-1
output = json
```
- [X] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
```
$ aws-vault exec %profile-name% --debug
2021/11/11 10:40:30 aws-vault v6.3.1
2021/11/11 10:40:30 Loading config file /home/vtvz/.aws/config
2021/11/11 10:40:30 Parsing config file /home/vtvz/.aws/config
2021/11/11 10:40:30 [keyring] Considering backends: [kwallet]
2021/11/11 10:40:36 Profile 'default' missing in config file
aws-vault: error: exec: Failed to get credentials for %profile-name%: unexpected end of JSON input
```

My freshly created profile with aws cli uses SSO for auth. And I cannot get what am I doing wrong, but every attempt ends with this "unexpected end of JSON input" error. I tried configure it manually and with aws cli. I tried different kinds of backend, but had no success.

**Comment by adridevdd** [comment]
Hi mate, 

I'm facing the same issue. In my case, I changed the backend from KWallet to file and it works again.

`export AWS_VAULT_BACKEND=file`

I hope it helps.

Cheers!

**Comment by adridevdd** [comment]
BTW I'm using Arch Linux 

Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.0
Codename:       Qonos

**Comment by jroimartin** [comment]
First of all, I'm not familiar with the code base of aws-vault. So, my answer might not be accurate.

It seems to me that this is caused by a bug in `github.com/99designs/keyring@v1.1.6` which was fixed in https://github.com/99designs/keyring/commit/ef00f8ac3d762e4e0997a49c16808bb7fe81b661. However, it's been a while since the last release of `github.com/99designs/keyring` and [aws-vault still depends on v1.1.6](https://github.com/99designs/aws-vault/blob/39a34315c76ac14143326737fe65def9de2d71ab/go.mod#L6).

I fixed it by cloning this repo and updating the dependency to `github.com/99designs/keyring@master`. You will also have to remove the [replace directive for `github.com/keybase/go-keychain`](https://github.com/99designs/aws-vault/blob/39a34315c76ac14143326737fe65def9de2d71ab/go.mod#L37), which is not required anymore.

**Comment by jroimartin** [comment]
@mtibben does my last comment make sense? do you plan to release a new version of keyring and aws-vault any time soon? This bug seems to be a game stopper for KDE users depending on kwallet.

BTW thanks for this great tool! :)
