### ISSUE TITLE
aws-vault in Windows WSL/Ubuntu 20.04 takes minutes to respond

### ISSUE THREAD

**Issue by djmills64** [99designs/aws-vault#857]
Hi,

If I run "aws-vault list" (or any other aws-vault command) on "Command Prompt I get an instant response. But via bash WSL it takes over a minute to respond.

I found a post that suggested that dbus might be the cause. I removed it but no improvement.

Any suggestions.

--debug didn't show anything useful.

I'm running Windows 11.

**Comment by thomaskvnze** [comment]
I have the exact same problem. I don't know what the problem is.

**Comment by thomaskvnze** [comment]
I got some debug output. When I started the wsl ubuntu and call aws-vault list the first time, I get this:

```
aws-vault list --debug
2022/02/07 19:21:58 aws-vault 6.5.0-Homebrew
2022/02/07 19:21:58 [keyring] Considering backends: [secret-service]
2022/02/07 19:21:58 Loading config file /home/thomaskunze/.aws/config
2022/02/07 19:21:58 Parsing config file /home/thomaskunze/.aws/config
2022/02/07 19:22:12 Unrecognised ini file section: DEFAULT
Profile                  Credentials              Sessions
=======                  ===========              ========
default                  -                        -
hidden                   -                        -
```

When I try to run the command again, I get this after a delay.

```
aws-vault list --debug
2022/02/07 19:24:27 aws-vault 6.5.0-Homebrew
2022/02/07 19:24:27 [keyring] Considering backends: [secret-service]
2022/02/07 19:26:27 [keyring] Failed backend secret-service: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
aws-vault: error: Specified keyring backend not available, try --help
```

**Comment by leviwilson** [comment]
I don't have the _same_ issue regarding `aws-vault list` (that's always fast for me) however I _do_ have something similar if I issue multiple `aws-vault exec` commands. For me, I have to `aws-vault clear` otherwise I can't connect again.

One thing that _did_ seem to help me just now (and I'm not 💯 why) but doing this got me past my issue and now it's very quick:

```
gpgconf --kill gpg-agent
```

Before it wasn't prompting me in the terminal to enter my `pass` password like it did before, but killing that agent did.

**Comment by z2665** [comment]
I use it in WSL2
On my environment aws-vault will wait for dbus-launch to start dbus, but if dbus-launch never finishes starting dbus then aws-vault will keep waiting.
So I traced the dbus-launch process using strace and found that he was stuck at this step
```
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110
```
After deleting the X0 file in /tmp/.X11-unix, run aws-vault again very process, the problem is solved

**Comment by tairosonloa** [comment]
Same issue, but none of the above solutions worked for me. Is anyone working on this? Has anyone workarounded it in another way?

**Comment by TM-23** [comment]
@tairosonloa did you ever find a workaround for this?

**Comment by tairosonloa** [comment]
> @tairosonloa did you ever find a workaround for this?

Sadly no. Ended using another tool for that, [awsume](https://awsu.me/)

**Comment by joshuajipp** [comment]
> Hi,
> 
> If I run "aws-vault list" (or any other aws-vault command) on "Command Prompt I get an instant response. But via bash WSL it takes over a minute to respond.
> 
> I found a post that suggested that dbus might be the cause. I removed it but no improvement.
> 
> Any suggestions.
> 
> --debug didn't show anything useful.
> 
> I'm running Windows 11.

I had the exact same issue and I believe it's a permissions issue. If you run it as admin with "sudo" , it should work

**Comment by whereisaaron** [comment]
> I use it in WSL2 On my environment aws-vault will wait for dbus-launch to start dbus, but if dbus-launch never finishes starting dbus then aws-vault will keep waiting. So I traced the dbus-launch process using strace and found that he was stuck at this step
> 
> ```
> connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110
> ```
> 
> After deleting the X0 file in /tmp/.X11-unix, run aws-vault again very process, the problem is solved

This problem happens often on WSL2. Deleting `rm /tmp/.X11-unix/X0` works for me too. I previous did an strace and sound aws-vault stuck on dbus. Not sure why it even tries to touch dbus when `AWS_VAULT_BACKEND=file`. But deleting this file fixes it instantly. Previously I used to stop and restart WSL2, or restart Windows to fix it.

**Comment by whereisaaron** [comment]
@mtibben can you unstale this please? This issue hasn't gone away. It frequent on WSL2 (Ubuntu). Not at boot, but a day or two later.

Two issues:
1. `aws-vault` engages dbus, even when dbus backend is not needed (`AWS_VAULT_BACKEND=file`)
2. `aws-vault` will often get stuck trying to connect to dbus and never times out, which would be fine, since dbus not needed anyway.

`strace` shows aws-vault is stuck on:
```
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/.X11-unix/X0"}, 110
```

The workaround is to delete this file `rm /tmp/.X11-unix/X0` which instantly fixes the problem.
