### ISSUE TITLE
Latest published version (v6.6.0) in downloads for Windows x64 will not install on Windows 11 Pro

### ISSUE THREAD

**Issue by michael-crawford** [99designs/aws-vault#893]
- [X] I am using the latest release of AWS Vault
- [ ] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

It refuses to even install, so it seems the config is moot and debug output I can't provide.

When I double-click the installer, I get this message:
This app can't run on your PC.
To find a version for your PC, check with the software publisher.

**Comment by alex-piccione-rdx** [comment]
I had this error when I mistakenly used the "arm64" .exe file, on my Windows x64 Pro.
Using the "386" .exe file, Windows asks permission to proceed (the usual dialog) and then ... nothing. 
Same thing trying to use 5.4.4 version.

**Comment by alex-piccione** [comment]
Reading this discussion here: https://github.com/99designs/aws-vault/issues/124
I find out the .exe is not an installer and it IS actually the tool itself.
That's why it doesn't install !
Download the downloaded file to aws-vault.exe and run it in GitBash ([Quick Start in README page]($ ./aws-vault.exe add test-devop
Enter Access Key ID: )): 
```
$ ./aws-vault.exe add johnsmith
Enter Access Key ID: 
``
