### ISSUE TITLE
Cannot read property 'accessKeyId' of undefined 

### ISSUE THREAD

**Issue by adcanis** [99designs/aws-vault#928]
- [ Y ] I am using the latest release of AWS Vault
- [ Y ] I have provided my `.aws/config` (redacted if necessary)
- [ N ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

**DEBUG did not work**

**Environment**
M1 Mac - MacOS

**.aws/config**
```
[profile foo]
output=json
region=ca-central-1

[profile foo-dev]
source_profile=foo
role_arn=arn:aws:iam::**********:role/foo-dev-admin

[profile foo-qa]
source_profile=foo
role_arn=arn:aws:iam::**********:role/foo-qa-admin

[profile foo-prod]
source_profile=foo
role_arn=arn:aws:iam::**********:role/foo-prod-admin
```
No **.aws/credentials** file 

**The issue:**
After running `amplify status` after doing some updates, an update to the CLI was available and I ran it. Now when i run `aws-vault exec foo-dev` for example, and try to perform a command like `amplify push -y` 
I get error :
`Failed to get profile: Cannot read property 'accessKeyId' of undefined`

I have tried to `unset AWS_VAULT`, `aws-vault clear` and created a credentials file with the appropriate credentials for the primary profile. 

That produces an entirely different error which i believe is unrelated to aws-vault but non-the-less it is: 
`Name: ResourceNotFoundException : Message: User pool ca-central-1_****** does not exist.`

any help is appreciated. Everything worked fine prior to CLI update

**Comment by scottbw** [comment]
I have the same error. 

I pulled backend fine, made a few edits, tried to push and now every command results in  "Cannot read property 'accessKeyId' of undefined" whenever I select to use a profile.  Also running on Mac.

**Comment by adcanis** [comment]
@scottbw this issue is currently being discussed in the amplify GitHub as well. So far what we've come up with is 
1. removing your `amplify` directory and your `aws-exports` file from `src` 
2. Setup a `~/.aws/credentials` file and add your credentials
3. Run `amplify pull --appId ***** --envName ***`

That has at least worked to remove the accesskeyid error

**Comment by scottbw** [comment]
Just reported there @adcanis - sadly the solution doesn't work for me even doing those exact steps. I already had a credentials file which still works fine for everything apart from Amplify.

**Comment by BrianHHough** [comment]
This might be too late but what worked for me to fix this was disabling the Amplify Studio in the actual AWS Amplify service page. 

I was getting the same error but the issue was an incompatibility between the Amplify CLI  and the AWS Management Console.

To debug a bit:
* log out of all AWS Management Console Sessions
* run `amplify logout —appId APPIDHERE` to make sure you are logged out
* disable the Amplify Studio switch in the Amplify app page in the AWS Management Console
* try to do the `amplify pull —appId APPIDHERE` command at the root of your repo

Make sure that your `/.aws/credentials` has the 2 keys that link to an associated IAM role with the right permissions of the expected behavior (i.e. Amplify Administrator Access), and that the `/.aws/config` has the right region you expect to use for that profile.

Hopefully this helps anyone else getting that error before (spent 3 hours this morning debugging this).
